name: MiningDrops
version: 1.0.3
main: pl.hansg.miningdrops.MiningDropsPlugin
api-version: '26.1.2'
author: HansG
description: Auto-pickup and configurable mining bonus drops.

commands:
  miningdrops:
    description: Main MiningDrops command
    usage: /miningdrops <auto|nocobble|reload|status|info>
    aliases: [mdrops, ap]

permissions:
  miningdrops.use:
    description: Allows auto-pickup for broken blocks
    default: true

  miningdrops.auto:
    description: Allows player to toggle auto-pickup
    default: false

  miningdrops.nocobble:
    description: Allows player to toggle cobblestone and other blocked materials pickup
    default: false

  miningdrops.info:
    description: Allows player to check configured block bonus drops
    default: true

  miningdrops.bonus:
    description: Allows player to receive bonus drops
    default: true

  miningdrops.admin:
    description: Allows reloading MiningDrops
    default: op