name: MiningDrops
version: 1.0.0
main: pl.hans.miningdrops.MiningDropsPlugin
api-version: '26.1.2'
author: HansG
description: Auto-pickup and configurable mining bonus drops.

commands:
  miningdrops:
    description: Main MiningDrops command
    usage: /miningdrops <toggle|reload|status|info>
    aliases: [mdrops, ap]

permissions:
  miningdrops.use:
    description: Allows auto-pickup for broken blocks
    default: true

  miningdrops.toggle:
    description: Allows player to toggle auto-pickup
    default: true

  miningdrops.info:
    description: Allows player to check configured block bonus drops
    default: true

  miningdrops.bonus:
    description: Allows player to receive bonus drops
    default: true

  miningdrops.admin:
    description: Allows reloading MiningDrops
    default: op